"""
Snowflake Feature Store Bridge
===============================

Python backend for skiPatrol::R/features.R.

This module wraps the snowflake.ml.feature_store Python API, providing
functions callable from R via reticulate. Each function receives a Snowpark
session object (from the sfr_connection) and performs Feature Store operations.

Key design decisions:
  - All pandas DataFrames returned to R are converted via JSON round-trip
    (pandas_to_r_dict) to avoid NumPy 1.x/2.x ABI issues with reticulate.
  - The FeatureStore object is instantiated per-call or cached in the R-side
    connection object to avoid stale references.
  - FeatureView source data is passed as SQL strings from R (generated by
    dbplyr or written manually), then wrapped in session.sql().
"""

import importlib.metadata
from typing import Dict, List, Optional, Any

try:
    _ML_VERSION_STR = importlib.metadata.version("snowflake-ml-python")
    _ML_VERSION = tuple(int(x) for x in _ML_VERSION_STR.split(".")[:3])
except Exception:
    _ML_VERSION_STR = "unknown"
    _ML_VERSION = (0, 0, 0)


def _requires(min_version, feature_name):
    """Raise RuntimeError if the installed snowflake-ml-python is too old."""
    if _ML_VERSION < min_version:
        need = ".".join(str(x) for x in min_version)
        raise RuntimeError(
            f"{feature_name} requires snowflake-ml-python >= {need}, "
            f"you have {_ML_VERSION_STR}. "
            f"Upgrade: pip install 'snowflake-ml-python>={need}'"
        )


# =============================================================================
# Internal helpers
# =============================================================================


def _to_json_tempfile(pdf):
    """Write a pandas DataFrame to a temp JSON file and return the path.

    Avoids the ``basic_string::substr`` C++ crash in reticulate/rpy2 that
    occurs when large dicts cross the Python <-> R bridge in Workspace
    Notebooks.  The R side reads and parses the file with jsonlite.
    """
    import json
    import tempfile

    d = _pandas_to_r_dict(pdf)
    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", delete=False, prefix="sfr_features_"
    )
    json.dump(d, tmp)
    tmp.close()
    return tmp.name


def _pandas_to_r_dict(pdf):
    """Convert a pandas DataFrame to a column-oriented dict with native Python
    types via Series.tolist().  This avoids NumPy ABI issues with reticulate
    and is more efficient than the previous JSON round-trip approach.

    Datetime columns are converted to ISO-format strings to avoid ugly
    POSIX timestamp objects in R output.

    NOTE: For very large datasets, an Apache Arrow IPC transfer (pyarrow on
    the Python side, arrow R package on the R side) would be significantly
    faster.  See TODO.md for the roadmap item.
    """
    import datetime

    _NA = "NA_SENTINEL_"
    clean_cols = [c.strip('"') for c in pdf.columns]
    pdf.columns = clean_cols
    cols = list(clean_cols)
    nrows = len(pdf)

    if nrows == 0:
        return {"columns": cols, "data": {c: [] for c in cols}, "nrows": 0}

    data = {}
    for col in cols:
        na_mask = pdf[col].isna()
        vals = pdf[col].tolist()

        # Convert datetime objects to ISO strings
        if vals and isinstance(vals[0], (datetime.datetime, datetime.date)):
            vals = [v.isoformat() if isinstance(v, (datetime.datetime, datetime.date)) else v for v in vals]

        if na_mask.any():
            data[col] = [_NA if is_na else (_NA if v is None else v)
                         for v, is_na in zip(vals, na_mask)]
        else:
            data[col] = [_NA if v is None else v for v in vals]

    return {"columns": cols, "data": data, "nrows": nrows}


_fs_cache: Dict[tuple, Any] = {}


def _get_feature_store(
    session,
    database: str,
    schema: str,
    default_warehouse: str,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
):
    """
    Get or create a FeatureStore instance, cached by
    (session, db, schema, warehouse, mode).

    session is part of the cache key -- Positron/Workbench can keep this
    process alive across multiple sfr_connect() calls, and db/schema/
    warehouse are commonly identical across a reconnect to the same
    project, so without it a stale FeatureStore bound to a dead or
    unrelated session would be returned silently.

    Args:
        session: Active Snowpark Session.
        database: Database containing the Feature Store schema.
        schema: Schema name for the Feature Store.
        default_warehouse: Default warehouse for compute.
        creation_mode: "CREATE_IF_NOT_EXIST" or "FAIL_IF_NOT_EXIST".

    Returns:
        FeatureStore instance.
    """
    cache_key = (session, database, schema, default_warehouse, creation_mode)
    if cache_key in _fs_cache:
        return _fs_cache[cache_key]

    from snowflake.ml.feature_store import FeatureStore, CreationMode

    mode_map = {
        "CREATE_IF_NOT_EXIST": CreationMode.CREATE_IF_NOT_EXIST,
        "FAIL_IF_NOT_EXIST": CreationMode.FAIL_IF_NOT_EXIST,
    }
    mode = mode_map.get(creation_mode, CreationMode.FAIL_IF_NOT_EXIST)

    fs = FeatureStore(
        session=session,
        database=database,
        name=schema,
        default_warehouse=default_warehouse,
        creation_mode=mode,
    )
    _fs_cache[cache_key] = fs
    return fs


def _make_entity(name: str, join_keys: List[str], desc: Optional[str] = None):
    """Create a local (draft) Entity object."""
    from snowflake.ml.feature_store import Entity
    return Entity(name=name, join_keys=join_keys, desc=desc or "")


def _make_feature_view(
    session,
    name: str,
    entities: list,
    sql: str,
    refresh_freq: Optional[str] = None,
    warehouse: Optional[str] = None,
    timestamp_col: Optional[str] = None,
    desc: Optional[str] = None,
    feature_granularity: Optional[str] = None,
    features: Optional[list] = None,
    initialize: Optional[str] = None,
    refresh_mode: Optional[str] = None,
    cluster_by: Optional[List[str]] = None,
    online_config_dict: Optional[Dict[str, Any]] = None,
):
    """Create a local (draft) FeatureView object."""
    from snowflake.ml.feature_store import FeatureView

    feature_df = session.sql(sql)

    fv_kwargs: Dict[str, Any] = {
        "name": name,
        "entities": entities,
        "feature_df": feature_df,
        "refresh_freq": refresh_freq,
        "timestamp_col": timestamp_col,
        "desc": desc or "",
        "warehouse": warehouse,
    }
    if feature_granularity is not None:
        fv_kwargs["feature_granularity"] = feature_granularity
    if features is not None:
        fv_kwargs["features"] = features
    if initialize is not None:
        fv_kwargs["initialize"] = initialize
    if refresh_mode is not None:
        fv_kwargs["refresh_mode"] = refresh_mode
    if cluster_by is not None:
        fv_kwargs["cluster_by"] = list(cluster_by)
    if online_config_dict is not None:
        _requires((1, 18, 0), "Online feature serving (online_config on FV)")
        from snowflake.ml.feature_store.feature_view import OnlineConfig
        fv_kwargs["online_config"] = OnlineConfig(
            enable=online_config_dict.get("enable", True),
            target_lag=online_config_dict.get("target_lag"),
        )

    return FeatureView(**fv_kwargs)


# =============================================================================
# Entity operations
# =============================================================================

def register_entity(
    session,
    name: str,
    join_keys: List[str],
    desc: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "CREATE_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """
    Create and register an entity in the Feature Store.

    Args:
        session: Active Snowpark Session.
        name: Entity name.
        join_keys: List of join key column names.
        desc: Entity description.
        database: Feature Store database.
        schema: Feature Store schema.
        warehouse: Default warehouse.
        creation_mode: "CREATE_IF_NOT_EXIST" or "FAIL_IF_NOT_EXIST".

    Returns:
        Dict with entity info (name, join_keys, desc).
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    entity = _make_entity(name, join_keys, desc)
    registered = fs.register_entity(entity)

    return {
        "name": registered.name if hasattr(registered, 'name') else name,
        "join_keys": join_keys,
        "desc": desc or "",
    }


def get_entity(
    session,
    name: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """Retrieve a registered entity by name."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    entity = fs.get_entity(name)

    return {
        "name": entity.name,
        "join_keys": list(entity.join_keys),
        "desc": getattr(entity, 'desc', ''),
    }


def list_entities(
    session,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """List all entities in the Feature Store. Returns a pandas DataFrame."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    return _pandas_to_r_dict(fs.list_entities().to_pandas())


def delete_entity(
    session,
    name: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> None:
    """Delete an entity by name."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fs.delete_entity(name)


# =============================================================================
# Feature View operations
# =============================================================================

def register_feature_view(
    session,
    name: str,
    version: str,
    sql: str,
    entity_names: List[str],
    entity_join_keys: Optional[List[List[str]]] = None,
    refresh_freq: Optional[str] = None,
    warehouse: Optional[str] = None,
    timestamp_col: Optional[str] = None,
    desc: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    overwrite: bool = False,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
    feature_granularity: Optional[str] = None,
    aggregation_features: Optional[List[Dict[str, str]]] = None,
    block: bool = True,
    initialize: Optional[str] = None,
    refresh_mode: Optional[str] = None,
    cluster_by: Optional[List[str]] = None,
    online_config_dict: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Register a Feature View in the Snowflake Feature Store.

    Entities must already be registered. This function:
    1. Connects to the Feature Store.
    2. Retrieves the named entities.
    3. Creates a draft FeatureView from the SQL + entities.
    4. Registers (materialises) the FeatureView.

    Args:
        session: Active Snowpark Session.
        name: FeatureView name.
        version: Version string (e.g., "v1").
        sql: SQL defining the feature transformation.
        entity_names: List of registered entity names.
        entity_join_keys: Not used when entities are pre-registered.
        refresh_freq: Refresh frequency (e.g., "1 hour", "0 30 * * *").
        warehouse: Warehouse override.
        timestamp_col: Timestamp column for time-series features.
        desc: Description.
        database: Feature Store database.
        schema: Feature Store schema.
        overwrite: If True, overwrite existing version.
        creation_mode: FeatureStore creation mode.
        feature_granularity: Tile granularity for tile-based aggregation FVs.
        aggregation_features: List of dicts with name, agg, window (dtype ignored).

    Returns:
        Dict with registered FeatureView info.
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    if feature_granularity is not None:
        _requires((1, 24, 0), "Tile-based aggregation (feature_granularity)")

    features_list = None
    if aggregation_features:
        from snowflake.ml.feature_store import Feature
        from snowflake.ml.feature_store.feature import AggregationType
        features_list = [
            Feature(
                function=AggregationType[f["agg"].upper()],
                column=f["name"],
                window=f["window"],
            )
            for f in aggregation_features
        ]

    fs = _get_feature_store(session, db, sc, wh, creation_mode)

    # Retrieve registered entities
    entities = [fs.get_entity(en) for en in entity_names]

    fv = _make_feature_view(
        session=session,
        name=name,
        entities=entities,
        sql=sql,
        refresh_freq=refresh_freq,
        warehouse=wh,
        timestamp_col=timestamp_col,
        desc=desc,
        feature_granularity=feature_granularity,
        features=features_list,
        initialize=initialize,
        refresh_mode=refresh_mode,
        cluster_by=cluster_by,
        online_config_dict=online_config_dict,
    )

    registered_fv = fs.register_feature_view(
        feature_view=fv,
        version=version,
        overwrite=overwrite,
        block=block,
    )

    return {
        "name": registered_fv.name,
        "version": registered_fv.version,
        "status": str(registered_fv.status),
        "desc": getattr(registered_fv, 'desc', desc or ''),
    }


def get_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """Retrieve a registered FeatureView by name and version."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fv = fs.get_feature_view(name, version)

    return {
        "name": fv.name,
        "version": fv.version,
        "status": str(fv.status),
        "desc": getattr(fv, 'desc', ''),
        "timestamp_col": getattr(fv, 'timestamp_col', None),
        "_py_fv": fv,  # Keep Python object for downstream use
    }


def list_feature_views(
    session,
    entity_name: Optional[str] = None,
    feature_view_name: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """List Feature Views. Returns a pandas DataFrame."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    kwargs = {}
    if entity_name:
        kwargs["entity_name"] = entity_name
    if feature_view_name:
        kwargs["feature_view_name"] = feature_view_name

    return _pandas_to_r_dict(fs.list_feature_views(**kwargs).to_pandas())


def delete_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> None:
    """Delete a registered FeatureView."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fs.delete_feature_view(name, version)


def refresh_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
    store_type: str = "OFFLINE",
) -> None:
    """Manually refresh a FeatureView."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    kwargs: Dict[str, Any] = {}
    if store_type.upper() != "OFFLINE":
        _requires((1, 18, 0), "Online feature store refresh")
        from snowflake.ml.feature_store.feature_view import StoreType
        kwargs["store_type"] = StoreType.ONLINE
    fs.refresh_feature_view(name, version, **kwargs)


def read_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
    keys_dict: Optional[Dict[str, Any]] = None,
    feature_names: Optional[list] = None,
    store_type: str = "OFFLINE",
) -> Any:
    """Read data from a registered FeatureView. Returns pandas DataFrame.

    keys_dict is column-oriented {COL: [v1, v2]} from R; we transpose to
    row-oriented [[v1_col1, v1_col2], ...] as the Python SDK expects.
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)

    kwargs: Dict[str, Any] = {}

    if keys_dict is not None:
        cols = list(keys_dict.values())
        first = cols[0]
        n = len(first) if hasattr(first, '__len__') and not isinstance(first, str) else 1
        if n == 1:
            keys_list = [[str(c[0]) if hasattr(c, '__len__') and not isinstance(c, str) else str(c) for c in cols]]
        else:
            keys_list = [[str(col[i]) for col in cols] for i in range(n)]
        kwargs["keys"] = keys_list

    if feature_names is not None:
        if isinstance(feature_names, str):
            feature_names = [feature_names]
        kwargs["feature_names"] = list(feature_names)

    if store_type.upper() != "OFFLINE":
        _requires((1, 18, 0), "Online feature store reads")
        from snowflake.ml.feature_store.feature_view import StoreType
        kwargs["store_type"] = StoreType.ONLINE
    else:
        from snowflake.ml.feature_store.feature_view import StoreType
        kwargs["store_type"] = StoreType.OFFLINE

    return _pandas_to_r_dict(fs.read_feature_view(name, version, **kwargs).to_pandas())


def suspend_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> None:
    """Suspend a FeatureView's automatic refresh."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fs.suspend_feature_view(name, version)


def resume_feature_view(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> None:
    """Resume a suspended FeatureView's automatic refresh."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fs.resume_feature_view(name, version)


# =============================================================================
# Training data generation
# =============================================================================

def generate_training_set(
    session,
    spine_sql: str,
    feature_view_refs: List[Dict[str, str]],
    spine_timestamp_col: Optional[str] = None,
    spine_label_cols: Optional[List[str]] = None,
    save_as: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
    exclude_columns: Optional[List[str]] = None,
    include_feature_view_timestamp_col: bool = False,
    auto_prefix: bool = False,
    join_method: Optional[str] = None,
) -> Any:
    """Generate a training set by joining spine data with Feature Views."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    spine_df = session.sql(spine_sql)
    fvs = [fs.get_feature_view(ref["name"], ref["version"]) for ref in feature_view_refs]

    kwargs: Dict[str, Any] = {}
    if spine_timestamp_col:
        kwargs["spine_timestamp_col"] = spine_timestamp_col
    if spine_label_cols:
        kwargs["spine_label_cols"] = spine_label_cols
    if save_as:
        kwargs["save_as"] = save_as
    if exclude_columns:
        kwargs["exclude_columns"] = list(exclude_columns)
    if include_feature_view_timestamp_col:
        kwargs["include_feature_view_timestamp_col"] = True
    if auto_prefix:
        kwargs["auto_prefix"] = True
    if join_method:
        kwargs["join_method"] = join_method

    result_df = fs.generate_training_set(
        spine_df=spine_df,
        features=fvs,
        **kwargs,
    )

    return _to_json_tempfile(result_df.to_pandas())


# Module-level cache for Dataset objects so sfr_log_model can retrieve
# a Snowpark DataFrame for lineage without re-opening the Dataset.
# Keyed on session too -- see _get_feature_store's docstring for why a
# name:version key alone isn't safe across a reconnect in this process.
_DATASET_CACHE: Dict[tuple, Any] = {}


def generate_dataset(
    session,
    name: str,
    spine_sql: str,
    feature_view_refs: List[Dict[str, str]],
    version: Optional[str] = None,
    spine_timestamp_col: Optional[str] = None,
    spine_label_cols: Optional[List[str]] = None,
    desc: str = "",
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
    exclude_columns: Optional[List[str]] = None,
    include_feature_view_timestamp_col: bool = False,
    auto_prefix: bool = False,
    output_type: Optional[str] = None,
    join_method: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Generate an immutable, versioned Dataset from Feature Views.

    Unlike generate_training_set (which returns a transient DataFrame),
    this creates a Snowflake ML Dataset object that participates in
    ML Lineage: Feature View -> Dataset -> Model.

    The Dataset object is cached so that sfr_log_model can later retrieve
    a Snowpark DataFrame backed by it for sample_input_data.

    Returns:
        Dict with keys: json_path, dataset_name, dataset_version.
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)

    spine_df = session.sql(spine_sql)
    fvs = [
        fs.get_feature_view(ref["name"], ref["version"])
        for ref in feature_view_refs
    ]

    kwargs: Dict[str, Any] = {}
    if spine_timestamp_col:
        kwargs["spine_timestamp_col"] = spine_timestamp_col
    if spine_label_cols:
        kwargs["spine_label_cols"] = spine_label_cols
    if desc:
        kwargs["desc"] = desc
    if exclude_columns:
        kwargs["exclude_columns"] = list(exclude_columns)
    if include_feature_view_timestamp_col:
        kwargs["include_feature_view_timestamp_col"] = True
    if auto_prefix:
        kwargs["auto_prefix"] = True
    if output_type:
        kwargs["output_type"] = output_type
    if join_method:
        kwargs["join_method"] = join_method

    try:
        ds = fs.generate_dataset(
            name=name,
            spine_df=spine_df,
            features=fvs,
            version=version,
            **kwargs,
        )
    except Exception as e:
        if "already exists" in str(e):
            from snowflake.ml.dataset import load_dataset
            actual_ver = version or name
            fqn = f"{db}.{sc}.{name}"
            print(f"[skiPatrol] Dataset {fqn}:{actual_ver} "
                  "already exists, loading it.")
            ds = load_dataset(session, fqn, actual_ver)
        else:
            raise

    if ds.selected_version:
        actual_version = str(ds.selected_version.name)
    else:
        actual_version = version or name
    cache_key = (session, name, actual_version)
    _DATASET_CACHE[cache_key] = ds
    print(f"[skiPatrol] Dataset cached: {name}:{actual_version} "
          f"(type={type(ds).__name__})")

    # Use Snowpark DataFrame path instead of ds.read.to_pandas() to
    # avoid Ray trying to install rpy2 on worker nodes without R.
    # TODO: Add optional Parquet path via ds.read.files() + fsspec
    # for large datasets. See internal/devops/TODO.md.
    pdf = ds.read.to_snowpark_dataframe().to_pandas()
    json_path = _to_json_tempfile(pdf)

    return {
        "json_path": json_path,
        "dataset_name": name,
        "dataset_version": actual_version,
    }


def get_cached_dataset(session, name: str, version: str):
    """Retrieve a cached Dataset object for use as sample_input_data."""
    cache_key = (session, name, version)
    return _DATASET_CACHE.get(cache_key)


def retrieve_features(
    session,
    spine_sql: str,
    feature_view_refs: List[Dict[str, str]],
    spine_timestamp_col: Optional[str] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
    exclude_columns: Optional[List[str]] = None,
    include_feature_view_timestamp_col: bool = False,
    auto_prefix: bool = False,
    join_method: Optional[str] = None,
) -> Any:
    """
    Retrieve feature values for inference.

    Without spine_timestamp_col this performs a simple LEFT JOIN on entity
    keys and returns the current feature values.  When spine_timestamp_col
    is provided, point-in-time correct values are returned instead.

    Args:
        session: Active Snowpark Session.
        spine_sql: SQL for entity key values.
        feature_view_refs: List of dicts with "name" and "version" keys.
        spine_timestamp_col: Optional timestamp column for PIT lookup.
        database: Feature Store database.
        schema: Feature Store schema.
        warehouse: Default warehouse.

    Returns:
        pandas DataFrame with feature values.
    """
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)

    spine_df = session.sql(spine_sql)
    fvs = [fs.get_feature_view(ref["name"], ref["version"]) for ref in feature_view_refs]

    kwargs: Dict[str, Any] = {}
    if spine_timestamp_col:
        kwargs["spine_timestamp_col"] = spine_timestamp_col
    if exclude_columns:
        kwargs["exclude_columns"] = list(exclude_columns)
    if include_feature_view_timestamp_col:
        kwargs["include_feature_view_timestamp_col"] = True
    if auto_prefix:
        kwargs["auto_prefix"] = True
    if join_method:
        kwargs["join_method"] = join_method

    result_df = fs.retrieve_feature_values(
        spine_df=spine_df,
        features=fvs,
        **kwargs,
    )

    return _to_json_tempfile(result_df.to_pandas())


# =============================================================================
# Additional operations
# =============================================================================

def update_entity(
    session,
    name: str,
    desc: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> None:
    """Update an entity's description."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    entity = fs.get_entity(name)
    fs.update_entity(name, desc=desc)


def get_refresh_history(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    verbose: bool = False,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
    store_type: str = "OFFLINE",
) -> Any:
    """Get refresh history for a Feature View. Returns pandas DataFrame."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    kwargs: Dict[str, Any] = {"verbose": verbose}
    if store_type.upper() != "OFFLINE":
        _requires((1, 18, 0), "Online feature store refresh history")
        from snowflake.ml.feature_store.feature_view import StoreType
        kwargs["store_type"] = StoreType.ONLINE
    return _pandas_to_r_dict(fs.get_refresh_history(name, version, **kwargs).to_pandas())


def setup_feature_store_schema(
    session,
    database: str,
    schema: str,
    warehouse: str,
) -> None:
    """
    Set up the Feature Store schema and required objects.

    Calls the standalone setup_feature_store() helper from snowflake.ml.
    """
    from snowflake.ml.feature_store import setup_feature_store

    setup_feature_store(
        session=session,
        database=database,
        schema=schema,
        warehouse=warehouse,
    )


def update_feature_view(
    session,
    name: str,
    version: str,
    update_args: Optional[Dict[str, Any]] = None,
    online_config_dict: Optional[Dict[str, Any]] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """Update properties of an existing Feature View."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')

    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fv = fs.get_feature_view(name, version)

    if online_config_dict is not None:
        _requires((1, 18, 0), "Online feature serving")
        from snowflake.ml.feature_store.feature_view import OnlineConfig
        oc = OnlineConfig(
            enable=online_config_dict.get("enable", True),
            target_lag=online_config_dict.get("target_lag"),
        )
        fv = fs.update_feature_view(fv, online_config=oc)

    if update_args:
        if "refresh_freq" in update_args:
            fv = fs.update_feature_view(fv, refresh_freq=update_args["refresh_freq"])
        if "warehouse" in update_args:
            fv = fs.update_feature_view(fv, warehouse=update_args["warehouse"])
        if "desc" in update_args:
            fv = fs.update_feature_view(fv, desc=update_args["desc"])

    return {"name": name, "version": version, "status": "updated"}


# =============================================================================
# FeatureView methods
# =============================================================================

def attach_feature_desc(
    session,
    name: str,
    version: str,
    descs: Dict[str, str],
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> bool:
    """Attach per-feature descriptions to a registered Feature View."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')
    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fv = fs.get_feature_view(name, version)
    fv.attach_feature_desc(dict(descs))
    return True


def slice_feature_view(
    session,
    name: str,
    version: str,
    feature_names: list,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Dict[str, Any]:
    """Return a sliced FeatureView with only the named features."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')
    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fv = fs.get_feature_view(name, version)
    if isinstance(feature_names, str):
        feature_names = [feature_names]
    sliced = fv.slice(list(feature_names))
    sliced_name = getattr(sliced, 'name', name)
    sliced_version = getattr(sliced, 'version', version)
    sliced_features = list(getattr(sliced, 'feature_names', feature_names))
    return {
        "name": sliced_name,
        "version": sliced_version,
        "feature_names": sliced_features,
        "names_requested": feature_names,
        "_py_fv": sliced,
    }


def feature_view_lineage(
    session,
    name: str,
    version: str,
    direction: str = "both",
    domain_filter: Optional[List[str]] = None,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """Get upstream/downstream lineage for a Feature View."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')
    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fv = fs.get_feature_view(name, version)
    kwargs: Dict[str, Any] = {}
    if direction:
        kwargs["direction"] = direction
    if domain_filter:
        kwargs["domain_filter"] = list(domain_filter)
    result = fv.lineage(**kwargs)
    return _pandas_to_r_dict(result.to_pandas()) if hasattr(result, 'to_pandas') else str(result)


def list_fv_columns(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """List column metadata for a registered Feature View."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')
    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fv = fs.get_feature_view(name, version)
    result = fv.list_columns()
    return _pandas_to_r_dict(result.to_pandas()) if hasattr(result, 'to_pandas') else _pandas_to_r_dict(result)


def fv_to_df(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """Convert a Feature View to a pandas DataFrame via read_feature_view."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')
    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    return _pandas_to_r_dict(fs.read_feature_view(name, version).to_pandas())


def fv_query(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> str:
    """Get the underlying SQL query for a Feature View."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')
    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fv = fs.get_feature_view(name, version)
    return str(fv.query)


def fv_fully_qualified_name(
    session,
    name: str,
    version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> str:
    """Get the fully qualified name of a Feature View."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')
    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    fv = fs.get_feature_view(name, version)
    return str(fv.fully_qualified_name())


def load_feature_views_from_dataset(
    session,
    dataset_name: str,
    dataset_version: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    warehouse: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> Any:
    """Load Feature Views associated with a Dataset."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    wh = warehouse or session.get_current_warehouse().replace('"', '')
    fs = _get_feature_store(session, db, sc, wh, creation_mode)
    from snowflake.ml.dataset import load_dataset
    fqn = f"{db}.{sc}.{dataset_name}"
    ds = load_dataset(session, fqn, dataset_version)
    fvs = fs.load_feature_views_from_dataset(ds)
    return [{"name": fv.name, "version": fv.version} for fv in fvs]


def update_default_warehouse(
    session,
    warehouse_name: str,
    database: Optional[str] = None,
    schema: Optional[str] = None,
    creation_mode: str = "FAIL_IF_NOT_EXIST",
) -> bool:
    """Update the default warehouse for the Feature Store."""
    db = database or session.get_current_database().replace('"', '')
    sc = schema or session.get_current_schema().replace('"', '')
    fs = _get_feature_store(session, db, sc, warehouse_name, creation_mode)
    fs.update_default_warehouse(warehouse_name)
    return True
